apiVersion: v1
kind: Service
metadata:
  name: billboarddevops
spec:
  type: LoadBalancer
  ports:
  - port: 5080
    protocol: TCP
    targetPort: 5080
  selector:
    app: billboarddevops

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: billboarddeploy
spec:
  selector:
    matchLabels:
      app: billboarddevops
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: billboarddevops
    spec:
      containers:
      - image: surajsnair23/billboardsn:latest
        imagePullPolicy: Always
        name: billboarddevops
        ports:
          - containerPort: 5080