apiVersion: v1
kind: Service
metadata:
  name: aspdevops
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: aspdevops

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspdeploy
spec:
  selector:
    matchLabels:
      app: aspdevops
  replicas: 2
  minReadySeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: aspdevops
    spec:
      containers:
      - image: surajsnair23/dotnetsn:latest
        imagePullPolicy: Always
        name: aspdevops
        ports:
          - containerPort: 80