apiVersion: v1
kind: Service
metadata:
  name: mongodevops
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodevops
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongodeploy
spec:
  selector:
    matchLabels:
      app: mongodevops
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodevops
    spec:
      containers:
      - image: mongo:latest
        name: mongodevops
        ports:
        - containerPort: 27017
    