apiVersion: v1
kind: Service
metadata:
  name: reactdevops
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: reactdevops

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactdeploy
spec:
  selector:
    matchLabels:
      app: reactdevops
  replicas: 2
  minReadySeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: reactdevops
    spec:
      containers:
      - image: surajsnair23/reactsn:latest
        imagePullPolicy: Always
        name: reactdevops
        ports:
          - containerPort: 80