apiVersion: v1
kind: Service
metadata:
  name: sentimentdevops
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: sentimentdevops

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimentdeploy
spec:
  selector:
    matchLabels:
      app: sentimentdevops
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sentimentdevops
    spec:
      containers:
      - image: surajsnair23/sentimentsn:latest
        imagePullPolicy: Always
        name: sentimentdevops
        ports:
          - containerPort: 5050